2022-06-02 10:09:31,265: [14] m.main:INFO: Registered plugins: IntrospectionAPIPlugin, <class 'manticore.ethereum.plugins.SkipRevertBasicBlocks'>, <class 'manticore.ethereum.plugins.FilterFunctions'>
2022-06-02 10:09:31,265: [14] m.main:INFO: Beginning analysis
2022-06-02 10:09:31,269: [14] m.e.manticore:INFO: Starting symbolic create contract
2022-06-02 10:09:35,159: [14] m.e.manticore:INFO: Starting symbolic transaction: 0
2022-06-02 10:12:06,753: [14] m.e.manticore:INFO: 8 alive states, 1 terminated states
2022-06-02 10:12:09,095: [14] m.e.manticore:INFO: Starting symbolic transaction: 1
2022-06-02 10:34:47,587: [14] m.c.worker:ERROR: Exception in state 11: ManticoreError('Forking on unfeasible constraint set')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 137, in run
    current_state.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/ethereum/state.py", line 8, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 3106, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.7/dist-packages/manticore/platforms/evm.py", line 1322, in execute
    raise Concretize("Symbolic PC", expression=expression, setstate=setstate, policy="ALL")
manticore.core.state.Concretize

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/worker.py", line 158, in run
    m._fork(current_state, exc.expression, exc.policy, exc.setstate, exc.values)
  File "/usr/local/lib/python3.7/dist-packages/manticore/core/manticore.py", line 518, in _fork
    raise ManticoreError("Forking on unfeasible constraint set")
manticore.exceptions.ManticoreError: Forking on unfeasible constraint set
 
2022-06-02 10:39:13,855: [14] m.e.manticore:INFO: 61 alive states, 5 terminated states
2022-06-02 10:39:16,696: [14] m.e.manticore:INFO: Starting symbolic transaction: 2